AddCSLuaFile()

function GM:RegisterAttsCW2FAS2()
    -- Attachments (only register stuff that isn't going to be left at default 2k price)
    self:RegisterAttachment({attachmentName = "am_fas2_9bizon", price = 500})
    self:RegisterAttachment({attachmentName = "am_fas2_9p226", price = 500})
    self:RegisterAttachment({attachmentName = "am_fas2_40mp5", price = 1000})
    self:RegisterAttachment({attachmentName = "am_fas2_45ragingbull", price = 0}) -- lol
    self:RegisterAttachment({attachmentName = "am_fas2_50ar", price = 1500})
    self:RegisterAttachment({attachmentName = "am_fas2_68ar", price = 1500})
    self:RegisterAttachment({attachmentName = "am_fas2_300ar", price = 1000})
    self:RegisterAttachment({attachmentName = "am_fas2_357deagle", price = 500})
    self:RegisterAttachment({attachmentName = "am_fas2_429deagle", price = 1000})
    self:RegisterAttachment({attachmentName = "am_fas2_ks23barrikada", price = 1000})
    self:RegisterAttachment({attachmentName = "am_fas2_ks23shrap25", price = 1000})

    self:RegisterAttachment({attachmentName = "bg_fas2_acog", price = 1500})
    self:RegisterAttachment({attachmentName = "bg_fas2_bipod", price = 1500})
    self:RegisterAttachment({attachmentName = "bg_fas2_compm4", price = 1000})
    self:RegisterAttachment({attachmentName = "bg_fas2_elcan", price = 1500})
    self:RegisterAttachment({attachmentName = "bg_fas2_eotech", price = 800})
    self:RegisterAttachment({attachmentName = "bg_fas2_foregrip", price = 1500})
    self:RegisterAttachment({attachmentName = "bg_fas2_leupold", price = 1500})
    self:RegisterAttachment({attachmentName = "bg_fas2_lmgx200mag", price = 2500})
    self:RegisterAttachment({attachmentName = "bg_fas2_parabarrel", price = 1000})
    self:RegisterAttachment({attachmentName = "bg_fas2_parastock", price = 500})
    self:RegisterAttachment({attachmentName = "bg_fas2_m2120mag", price = 1000})
    self:RegisterAttachment({attachmentName = "bg_fas2_macstock", price = 0})
    self:RegisterAttachment({attachmentName = "bg_fas2_mp5k30mag", price = 1000})
    self:RegisterAttachment({attachmentName = "bg_fas2_mp5kpdwstock", price = 1000})
    self:RegisterAttachment({attachmentName = "bg_fas2_mp5sd", price = 1500})
    self:RegisterAttachment({attachmentName = "bg_fas2_pso1", price = 1500})
    self:RegisterAttachment({attachmentName = "bg_fas2_sig55xgrip_sniper", price = 500})
    self:RegisterAttachment({attachmentName = "bg_fas2_sig55xmag", price = 1000})
    self:RegisterAttachment({attachmentName = "bg_fas2_sig55xstock_sniper", price = 500})
    self:RegisterAttachment({attachmentName = "bg_fas2_sks20mag", price = 500})
    self:RegisterAttachment({attachmentName = "bg_fas2_sks30mag", price = 1000})
    self:RegisterAttachment({attachmentName = "bg_fas2_sr2520mag", price = 1000})
    self:RegisterAttachment({attachmentName = "bg_fas2_suppressor", price = 1500})
    self:RegisterAttachment({attachmentName = "bg_fas2_tritiumsights", price = 0})
    self:RegisterAttachment({attachmentName = "bg_fas2_uziwoodstock", price = 1000})

    self:RegisterAttachment({attachmentName = "md_fas2_suppressor", price = 1500})
    self:RegisterAttachment({attachmentName = "md_fas2_muzzlebrake", price = 1500})
    self:RegisterAttachment({attachmentName = "md_fas2_compensator", price = 1500})
end