AddCSLuaFile()

-- Hey its my weapon pack
function GM:RegisterWepsCW2FAS2()
    -- experimenting with a disgusting one-line format to cut down on variable allocation
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_ak12", weight = 3.3, pointCost = 29})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_ak47", weight = 3.5, pointCost = 24})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_aks74", weight = 3, pointCost = 24})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_an94", weight = 3.3, pointCost = 27})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_cf05", weight = 2.1, pointCost = 15})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_famas",  weight = 3.61, pointCost = 27})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_g3a3", weight = 4.1, pointCost = 32})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_g36c", weight = 2.82, pointCost = 24})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_galil", weight = 4.35, pointCost = 24})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_kacpdw", weight = 2, pointCost = 18})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_ks23", weight = 3.85, pointCost = 15})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m3", weight = 3.27, pointCost = 15})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m4a1", weight = 3.01, pointCost = 26})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m14", weight = 4.1, pointCost = 32})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m16a2", weight = 6.37, pointCost = 25, penMod = 1.1})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m24", weight = 6.37, pointCost = 25, penMod = 1.1})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m60e3", weight = 10.5, pointCost = 37, maxMags = 2})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m82", weight = 13.5, pointCost = 45})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m249", weight = 7.5, pointCost = 32, maxMags = 2})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_m870", weight = 3.2, pointCost = 14})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_mac11", weight = 1.59, pointCost = 12})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_mp5a5", weight = 2.5, pointCost = 15, penMod = 1.2})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_mp5k", weight = 2, pointCost = 13})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_pp19", weight = 2.1, pointCost = 15})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_rk95", weight = 3.7, pointCost = 25})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_rpk", weight = 4.8, pointCost = 29})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_sg550", weight = 3.3, pointCost = 27})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_sks", weight = 3.67, pointCost = 20})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_sr25", weight = 3.9, pointCost = 34, penMod = 1.1})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_sterling", weight = 2.7, pointCost = 12})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_sterlingmk7", weight = 2, pointCost = 11})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_svd", weight = 4, pointCost = 36, penMod = 1.1})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_toz34", weight = 3, pointCost = 12})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_uzi", weight = 3.5, pointCost = 13})
    self:RegisterPrimaryWeapon({weaponClass = "cw_fas2_vollmer", weight = 4.9, pointCost = 38})

    self:RegisterSecondaryWeapon({weaponClass = "cw_fas2_deagle", weight = 2, pointCost = 10})
    self:RegisterSecondaryWeapon({weaponClass = "cw_fas2_glock20", weight = 0.78, pointCost = 8})
    self:RegisterSecondaryWeapon({weaponClass = "cw_fas2_m1911", weight = 1.105, pointCost = 4})
    self:RegisterSecondaryWeapon({weaponClass = "cw_fas2_ots33", weight = 1.15, pointCost = 6})
    self:RegisterSecondaryWeapon({weaponClass = "cw_fas2_p226", weight = 0.964, pointCost = 7})
    self:RegisterSecondaryWeapon({weaponClass = "cw_fas2_ragingbull", weight = 1.5, pointCost = 7})

end

