util.AddNetworkString("GC_ADRENALINE")
util.AddNetworkString("GC_ALIVE_PLAYER_COUNT")
util.AddNetworkString("GC_ANNOUNCEMENT")
util.AddNetworkString("GC_ARMOR_PIECE") -- Used to pass info about armor AND helmet damage
util.AddNetworkString("GC_ARMOR") -- Send selected vest data
util.AddNetworkString("GC_ATTACHMENTS")
util.AddNetworkString("GC_BANDAGES")
util.AddNetworkString("GC_BLEEDSTATE")
util.AddNetworkString("GC_CASH")
util.AddNetworkString("GC_DRUGS_REMOVED")
util.AddNetworkString("GC_EVENT")
util.AddNetworkString("GC_EXPERIENCE")
util.AddNetworkString("GC_GADGETS")
util.AddNetworkString("GC_GAME_BEGIN")
util.AddNetworkString("GC_HELMET") -- Send selected helmet data
util.AddNetworkString("GC_KILLED_BY")
util.AddNetworkString("GC_LAST_MAN_STANDING")
util.AddNetworkString("GC_MVP")
util.AddNetworkString("GC_NEW_ROUND")
util.AddNetworkString("GC_NOT_ENOUGH_CASH")
util.AddNetworkString("GC_NOTIFICATION")
util.AddNetworkString("GC_RETRYTEAMSELECTION")
util.AddNetworkString("GC_ROUND_OVER")
util.AddNetworkString("GC_ROUND_PREPARATION")
util.AddNetworkString("GC_ROUNG_OVER")
util.AddNetworkString("GC_SPECTATE_TARGET")
util.AddNetworkString("GC_STAMINA")
util.AddNetworkString("GC_STATUS_EFFECT_ON_PLAYER")
util.AddNetworkString("GC_TEAM_SELECTION_SUCCESS")
util.AddNetworkString("GC_TRAITS")
util.AddNetworkString("GC_UNLOCK_ATTACHMENT")
util.AddNetworkString("GC_UNLOCKED_SLOTS")
util.AddNetworkString("GC_VOTE")
util.AddNetworkString("GC_NEW_TEAM")