bot_profiles = {
    {name = "Xaero", accuracy = 1},
    {name = "Ranger", accuracy = 1},
    {name = "Doomguy", accuracy = 1},
    {name = "Blazko", accuracy = 1},
    {name = "Pepe", accuracy = 1},
    {name = "Timmy", accuracy = 1},
    {name = "Visor", accuracy = 0.8},
    {name = "Keel", accuracy = 0.8},
    {name = "Anarki", accuracy = 0.8},
    {name = "Johnson", accuracy = 0.5},
    {name = "Moore", accuracy = 0.5},
    {name = "Smith", accuracy = 0.5},
    {name = "Bana", accuracy = 0.5},
    {name = "Konig", accuracy = 0.5},
    {name = "Teebagy", accuracy = 0.5},
    {name = "Polloni", accuracy = 0.5},
    {name = "Rykov", accuracy = 0.5},
    {name = "Ramirez", accuracy = 0.5},
    {name = "Lai", accuracy = 0.5},
    {name = "Kim", accuracy = 0.5},
    {name = "Chen", accuracy = 0.5},
    {name = "Yamada", accuracy = 0.5},
    {name = "Schmidt", accuracy = 0.5},
    {name = "Golubev", accuracy = 0.5},
    {name = "Kraft", accuracy = 0.25},
    {name = "Yang", accuracy = 0.25},
    {name = "Griffin", accuracy = 0.25},
    {name = "Matsushita", accuracy = 0.25},
    {name = "Buyanov", accuracy = 0.25},
    {name = "Boon", accuracy = 0.25},
    {name = "Newell", accuracy = 0.25},
    {name = "Adams", accuracy = 0.25},
    {name = "Pinkerton", accuracy = 0.25},
    {name = "Perez", accuracy = 0.25},
}

function getBotName()
    return table.Random(bot_profiles).name
end